version: '3.4'
services:
  metad:
    image: vesoft/nebula-metad:v3.6.0
    environment:
      USER: root
    command:
      - --meta_server_addrs=metad:9559
      - --local_ip=metad
      - --ws_ip=metad
      - --port=9559
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://metad:19559/status"]
      interval: 30s
      timeout: 10s
      retries: 3
    ports:
      - 9559:9559
      - 19559:19559
    networks:
      - nebula-net

  storaged:
    image: vesoft/nebula-storaged:v3.6.0
    environment:
      USER: root
    command:
      - --meta_server_addrs=metad:9559
      - --local_ip=storaged
      - --ws_ip=storaged
      - --port=9779
    depends_on:
      - metad
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://storaged:19779/status"]
      interval: 30s
      timeout: 10s
      retries: 3
    ports:
      - 9779:9779
      - 19779:19779
    networks:
      - nebula-net

  graphd:
    image: vesoft/nebula-graphd:v3.6.0
    environment:
      USER: root
    command:
      - --meta_server_addrs=metad:9559
      - --local_ip=graphd
      - --ws_ip=graphd
      - --port=9669
    depends_on:
      - storaged
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://graphd:19669/status"]
      interval: 30s
      timeout: 10s
      retries: 3
    ports:
      - 9669:9669
      - 19669:19669
    networks:
      - nebula-net

networks:
  nebula-net:
